# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_core/proto/optimizer_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_tao_core.proto import sgd_optimizer_config_pb2 as nvidia__tao__core_dot_proto_dot_sgd__optimizer__config__pb2
from nvidia_tao_core.proto import adam_optimizer_config_pb2 as nvidia__tao__core_dot_proto_dot_adam__optimizer__config__pb2
from nvidia_tao_core.proto import rmsprop_optimizer_config_pb2 as nvidia__tao__core_dot_proto_dot_rmsprop__optimizer__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nvidia_tao_core/proto/optimizer_config.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n,nvidia_tao_core/proto/optimizer_config.proto\x1a\x30nvidia_tao_core/proto/sgd_optimizer_config.proto\x1a\x31nvidia_tao_core/proto/adam_optimizer_config.proto\x1a\x34nvidia_tao_core/proto/rmsprop_optimizer_config.proto\"\x94\x01\n\x0fOptimizerConfig\x12$\n\x04\x61\x64\x61m\x18\x01 \x01(\x0b\x32\x14.AdamOptimizerConfigH\x00\x12\"\n\x03sgd\x18\x02 \x01(\x0b\x32\x13.SGDOptimizerConfigH\x00\x12*\n\x07rmsprop\x18\x03 \x01(\x0b\x32\x17.RMSpropOptimizerConfigH\x00\x42\x0b\n\toptimizerb\x06proto3')
  ,
  dependencies=[nvidia__tao__core_dot_proto_dot_sgd__optimizer__config__pb2.DESCRIPTOR,nvidia__tao__core_dot_proto_dot_adam__optimizer__config__pb2.DESCRIPTOR,nvidia__tao__core_dot_proto_dot_rmsprop__optimizer__config__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OPTIMIZERCONFIG = _descriptor.Descriptor(
  name='OptimizerConfig',
  full_name='OptimizerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adam', full_name='OptimizerConfig.adam', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sgd', full_name='OptimizerConfig.sgd', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rmsprop', full_name='OptimizerConfig.rmsprop', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optimizer', full_name='OptimizerConfig.optimizer',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=204,
  serialized_end=352,
)

_OPTIMIZERCONFIG.fields_by_name['adam'].message_type = nvidia__tao__core_dot_proto_dot_adam__optimizer__config__pb2._ADAMOPTIMIZERCONFIG
_OPTIMIZERCONFIG.fields_by_name['sgd'].message_type = nvidia__tao__core_dot_proto_dot_sgd__optimizer__config__pb2._SGDOPTIMIZERCONFIG
_OPTIMIZERCONFIG.fields_by_name['rmsprop'].message_type = nvidia__tao__core_dot_proto_dot_rmsprop__optimizer__config__pb2._RMSPROPOPTIMIZERCONFIG
_OPTIMIZERCONFIG.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZERCONFIG.fields_by_name['adam'])
_OPTIMIZERCONFIG.fields_by_name['adam'].containing_oneof = _OPTIMIZERCONFIG.oneofs_by_name['optimizer']
_OPTIMIZERCONFIG.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZERCONFIG.fields_by_name['sgd'])
_OPTIMIZERCONFIG.fields_by_name['sgd'].containing_oneof = _OPTIMIZERCONFIG.oneofs_by_name['optimizer']
_OPTIMIZERCONFIG.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZERCONFIG.fields_by_name['rmsprop'])
_OPTIMIZERCONFIG.fields_by_name['rmsprop'].containing_oneof = _OPTIMIZERCONFIG.oneofs_by_name['optimizer']
DESCRIPTOR.message_types_by_name['OptimizerConfig'] = _OPTIMIZERCONFIG

OptimizerConfig = _reflection.GeneratedProtocolMessageType('OptimizerConfig', (_message.Message,), dict(
  DESCRIPTOR = _OPTIMIZERCONFIG,
  __module__ = 'nvidia_tao_core.proto.optimizer_config_pb2'
  # @@protoc_insertion_point(class_scope:OptimizerConfig)
  ))
_sym_db.RegisterMessage(OptimizerConfig)


# @@protoc_insertion_point(module_scope)
