# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_core/proto/rmsprop_optimizer_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nvidia_tao_core/proto/rmsprop_optimizer_config.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n4nvidia_tao_core/proto/rmsprop_optimizer_config.proto\"Z\n\x16RMSpropOptimizerConfig\x12\x0b\n\x03rho\x18\x01 \x01(\x02\x12\x10\n\x08momentum\x18\x02 \x01(\x02\x12\x0f\n\x07\x65psilon\x18\x03 \x01(\x02\x12\x10\n\x08\x63\x65ntered\x18\x04 \x01(\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RMSPROPOPTIMIZERCONFIG = _descriptor.Descriptor(
  name='RMSpropOptimizerConfig',
  full_name='RMSpropOptimizerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rho', full_name='RMSpropOptimizerConfig.rho', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='RMSpropOptimizerConfig.momentum', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='RMSpropOptimizerConfig.epsilon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='centered', full_name='RMSpropOptimizerConfig.centered', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['RMSpropOptimizerConfig'] = _RMSPROPOPTIMIZERCONFIG

RMSpropOptimizerConfig = _reflection.GeneratedProtocolMessageType('RMSpropOptimizerConfig', (_message.Message,), dict(
  DESCRIPTOR = _RMSPROPOPTIMIZERCONFIG,
  __module__ = 'nvidia_tao_core.proto.rmsprop_optimizer_config_pb2'
  # @@protoc_insertion_point(class_scope:RMSpropOptimizerConfig)
  ))
_sym_db.RegisterMessage(RMSpropOptimizerConfig)


# @@protoc_insertion_point(module_scope)
